swagger_parser:
  schema_path: ../docs/openapi.yaml
  output_directory: lib/api
  name: task_tracker
  language: dart
  json_serializer: freezed
  root_client: true
  root_client_name: TaskTrackerClient
  client_postfix: Client
  export_file: true
  mark_files_as_generated: true
  unknown_enum_value: true
  enums_to_json: true
  enums_parent_prefix: true
  put_clients_in_folder: true
  merge_clients: false
